spring:
  application:
    name: es-rest-client-demo
server:
  port: 8082

# 健康管理
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always

# elasticsearch 相关配置
elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: 127.0.0.1:9200
  index:
    number-of-replicas: 2
    number-of-shards: 3
  account:
    username:
    password:



